spring:
  jackson:
    read:
      ALLOW_UNESCAPED_CONTROL_CHARS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB

server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks,mappings"


logging:
  level:
    root: INFO
    com.amazonaws: ERROR
    org.springframework: INFO
    com.wutsi: DEBUG

  pattern:
    console: "%d Type=%level Logger=%c Thread=%thread %m%n"
    file: "%d Type=%level Logger=%c Thread=%thread %m%n"

threadpool:
  value: "wutsi-ml-service"
  minPoolSize: 16
  maxPoolSize: 16
  queueSize: 100

wutsi:
  client-id: wutsi-ml-service
  application:
    name: wutsi-ml-service

  platform:
    cache:
      name: ${wutsi.application.name}
      type: local
    error:
      controller-advice:
        enabled: true
    security:
      type: none
    storage:
      type: local
      local:
        directory: "${user.home}/wutsi/storage"
    tracing:
      client-id: ${wutsi.application.name}

  crontab:
    embedding-tfidf: "0 30 2 * * *"        # Every day ar 2:30AM GMT
