ALTER TABLE T_PRODUCT ADD COLUMN total_sales BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_PRODUCT ADD COLUMN total_units BIGINT NOT NULL DEFAULT 0;
ALTER TABLE T_PRODUCT ADD COLUMN total_orders BIGINT NOT NULL DEFAULT 0;
