web: java -Xms400M -Xmx400M  -Dserver.port=$PORT -jar wutsi-ml-service.jar --spring.profiles.active=$APP_PROFILE

recommender-v1-model: java -Xms256M -Xmx256M -Dserver.port=$PORT -Dwutsi.platform.stream.consume=false -jar wutsi-ml-service.jar --spring.profiles.active=$APP_PROFILE -job=recommender-v1-model
embedding-tfidf:      java -Xms256M -Xmx256M -Dserver.port=$PORT -Dwutsi.platform.stream.consume=false -jar wutsi-ml-service.jar --spring.profiles.active=$APP_PROFILE -job=embedding-tfidf
