wutsi:
  application:
    server-url: https://wutsi-shell-bff-test.herokuapp.com
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
    image:
      type: image-kit
      image-kit:
        origin-url: "https://s3.amazonaws.com/int-wutsi"
        endpoint-url: "https://ik.imagekit.io/cx8qxsgz4d"
    messaging:
      url-shortener:
        type: bitly
        bitly:
          access-token: ${BITLY_ACCESS_TOKEN}
    security:
      api-key: ${API_KEY}
      token-blacklist:
        type: redis
        redis:
          url: ${REDISCLOUD_URL}
    storage:
      type: aws
      aws:
        bucket: int-wutsi
