package com.wutsi.blog.story.dto

import com.wutsi.blog.product.dto.Category
import com.wutsi.blog.story.dto.StoryAccess.PUBLIC
import java.util.Date

data class Story(
    val id: Long = -1,
    val userId: Long = -1,
    val title: String? = null,
    val tagline: String? = null,
    val summary: String? = null,
    val thumbnailUrl: String? = null,
    val sourceUrl: String? = null,
    val sourceSite: String? = null,
    val wordCount: Int = 0,
    val readingMinutes: Int = 0,
    val language: String? = null,
    var content: String? = null,
    val contentType: String? = null,
    val status: StoryStatus = StoryStatus.DRAFT,
    val creationDateTime: Date = Date(),
    val modificationDateTime: Date = Date(),
    val contentModificationDateTime: Date = Date(),
    val publishedDateTime: Date? = null,
    val tags: List<Tag> = emptyList(),
    val slug: String = "",
    val readabilityScore: Int = 0,
    val topic: Topic? = null,
    val scheduledPublishDateTime: Date? = null,
    val access: StoryAccess = PUBLIC,
    val video: Boolean = false,
    val pinned: Boolean = false,
    val likeCount: Long = 0,
    val liked: Boolean = false,
    val shared: Boolean = false,
    val commented: Boolean = false,
    val commentCount: Long = 0,
    val shareCount: Long = 0,
    val readCount: Long = 0,
    val recipientCount: Long = 0,
    val readerCount: Long = 0,
    val subscriberReaderCount: Long = 0,
    val emailReaderCount: Long = 0,
    val clickCount: Long = 0,
    val subscriberCount: Long = 0,
    val totalDurationSeconds: Long = 0,
    val wppScore: Int = 0,
    val attachmentDownloadCount: Long = 0,
    val category: Category? = null,
)
