DROP TABLE TMT_STORY_CONTENT;

ALTER TABLE T_STORY CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE T_STORY_CONTENT CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
