ALTER TABLE T_USER ADD COLUMN facebook_id VARCHAR(50);
ALTER TABLE T_USER ADD COLUMN twitter_id VARCHAR(50);
ALTER TABLE T_USER ADD COLUMN linkedin_id VARCHAR(50);
ALTER TABLE T_USER ADD COLUMN youtube_id VARCHAR(50);
