ALTER TABLE T_MAIL_UNSUBSCRIBED DROP INDEX email;

ALTER TABLE T_MAIL_UNSUBSCRIBED CHANGE email subscriber_email VARCHAR(255);

ALTER TABLE T_MAIL_UNSUBSCRIBED ADD COLUMN user_fk BIGINT NULL;
ALTER TABLE T_MAIL_UNSUBSCRIBED ADD CONSTRAINT T_MAIL_UNSUBSCRIBED__user_fk FOREIGN KEY (user_fk) REFERENCES T_USER(id);
CREATE INDEX T_MAIL_UNSUBSCRIBED__user_fk_subscriber_email ON T_MAIL_UNSUBSCRIBED(user_fk, subscriber_email);
