ALTER TABLE T_USER ADD COLUMN site_id BIGINT DEFAULT 1;

ALTER TABLE T_STORY ADD COLUMN site_id BIGINT DEFAULT 1;
ALTER TABLE T_STORY DROP INDEX I_STORY__source_url_hash;
CREATE INDEX I_STORY__source_url_hash ON T_STORY(site_id, source_url_hash);
