ALTER TABLE T_WALLET ADD COLUMN account_number VARCHAR(30);
ALTER TABLE T_WALLET ADD COLUMN account_type INT NOT NULL DEFAUTL 0;
ALTER TABLE T_WALLET ADD COLUMN last_cashout_date_time DATETIME;
ALTER TABLE T_WALLET ADD COLUMN next_cashout_date DATE;
