ALTER TABLE T_TRANSACTION ADD COLUMN ads_fk VARCHAR(36) REFERENCES T_ADS(id);
ALTER TABLE T_TRANSACTION MODIFY wallet_fk VARCHAR(36) NULL;

ALTER TABLE T_ADS ADD COLUMN transaction_fk VARCHAR(36) REFERENCES T_TRANSACTION(id);