ALTER TABLE T_WALLET ADD COLUMN account_number VARCHAR(30);
ALTER TABLE T_WALLET ADD COLUMN account_owner VARCHAR(100);
ALTER TABLE T_WALLET ADD COLUMN account_type INT NOT NULL DEFAULT 0;
ALTER TABLE T_WALLET ADD COLUMN last_cashout_date_time DATETIME;
ALTER TABLE T_WALLET ADD COLUMN next_cashout_date DATE;

ALTER TABLE T_WALLET ADD CONSTRAINT CHK_balance CHECK (balance>=0);
