ALTER TABLE T_TRANSACTION
    ADD COLUMN product_fk BIGINT REFERENCES T_PRODUCT (id);
ALTER TABLE T_TRANSACTION
    ADD COLUMN store_fk BIGINT REFERENCES T_STORE (id);

ALTER TABLE T_WALLET
    ADD COLUMN charge_count BIGINT NOT NULL DEFAULT 0;
