ALTER TABLE T_SESSION
    ADD COLUMN referer VARCHAR(50);

ALTER TABLE T_SESSION
    ADD COLUMN device_id VARCHAR(36);

ALTER TABLE T_SESSION
    ADD COLUMN ip VARCHAR(50);

ALTER TABLE T_SESSION
    ADD COLUMN story_id BIGINT;
