DELETE FROM T_MAIL_UNSUBSCRIBED;

DELETE FROM T_PIN;

DELETE FROM T_STORY_TAG;
DELETE FROM T_TAG;

DELETE FROM T_COMMENT;
DELETE FROM T_LIKE;
DELETE FROM T_FOLLOWER;

DELETE FROM T_STORY_CONTENT;
DELETE FROM T_STORY;

DELETE FROM T_FEED;
DELETE FROM T_CHANNEL;
DELETE FROM T_SESSION;
DELETE FROM T_ACCOUNT;
DELETE FROM T_USER;
