DELETE FROM T_MAIL_UNSUBSCRIBED;

DELETE FROM T_PIN;

DELETE FROM T_STORY_TAG;
DELETE FROM T_TAG;

DELETE FROM T_LIKE;
DELETE FROM T_LIKE_V2;

DELETE FROM T_COMMENT;
DELETE FROM T_COMMENT_V2;

DELETE FROM T_SUBSCRIPTION;
DELETE FROM T_FOLLOWER;

DELETE FROM T_SHARE;

UPDATE T_USER set pin_story_id=NULL;
DELETE FROM T_STORY_CONTENT;
DELETE FROM T_STORY;

DELETE FROM T_FEED;
DELETE FROM T_CHANNEL;
DELETE FROM T_SESSION;
DELETE FROM T_ACCOUNT;
DELETE FROM T_USER;

DELETE FROM T_EVENT;
