server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,flyway,health,info,scheduledtasks"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null


wutsi:
  client-id: membership-manager
  application:
    name: membership-manager
  platform:
    cache:
      name: ${wutsi.application.name}
      type: local
    security:
      type: jwt
      api-key: "--membership-manager-api-key--"
      verify-token: false
      public-endpoints:
        - "GET /v1/members/*"
        - "POST /v1/members"
        - "POST /v1/members/search"
    stream:
      name: ${wutsi.application.name}
      type: local
    tracing:
      client-id: ${wutsi.application.name}

logging:
  level:
    root: INFO
    com.wutsi.membership.manager: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


