spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}

wutsi:
  client-id: marketplace-access
  #  application:
  #    jobs:
  #      import-yesterday-sales-kpi:
  #        cron: "0 20 0 * * *"  # Runs every day at 00:20 AM
  #      import-today-sales-kpi:
  #        cron: "0 30 * * * *"  # Runs every hour at *:30
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
    security:
      type: none
    storage:
      type: aws
      aws:
        bucket: prod-wutsi-data

