wutsi:
  asset-url: https://${wutsi.storage.s3.bucket}.s3.amazonaws.com/static/wutsi-blog-web
  domain: com-wutsi-blog-web-prod.herokuapp.com
  base-url: https://${wutsi.domain}

  application:
    backend:
      base-url: https://wutsi-blog-service-prod.herokuapp.com

  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
    image:
      type: image-kit
      image-kit:
        origin-url: "https://s3.amazonaws.com/prod-wutsi"
        endpoint-url: "https://ik.imagekit.io/toifevuwjn"
    storage:
      type: aws
      aws:
        bucket: prod-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}

  oauth:
    github:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}
    facebook:
      client-id: ${FACEBOOK_CLIENT_ID}
      client-secret: ${FACEBOOK_CLIENT_SECRET}
    google:
      api-key: ${GOOGLE_API_KEY}
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
    linkedin:
      client-id: ${LINKEDIN_CLIENT_ID}
      client-secret: ${LINKEDIN_CLIENT_SECRET}
    twitter:
      client-id: ${TWITTER_CLIENT_ID}
      client-secret: ${TWITTER_CLIENT_SECRET}
    yahoo:
      client-id: ${YAHOO_CLIENT_ID}
      client-secret: ${YAHOO_CLIENT_SECRET}

  google:
    ga:
      code: "UA-120456146-1"

  facebook:
    app-id: "466330503408293"
    pixel:
      code: "553466401984152"

  toggles:
    channel: true
    channel-twitter: true
    channel-facebook: false
    channel-linkedin: true
    channel-telegram: false
    create-blog: false
    comment: true
    earning: false
    event-stream-tracking: false
    facebook-pixel: false
    follow: true
    follow-popup: false
    google-one-tap-sign-in: true
    imagekit: true
    like: true
    pin: false
    pwa: true
    pwa-add-to-homescreen: false
    pwa-badge: false
    pwa-push-notification: false
    statistics: false
    recommendation: true
    publish: true
    sso-facebook: false
    sso-google: true
    sso-github: false
    sso-twitter: false
    sso-yahoo: true
    translation: false    # Cost saving
    tracking: false       # Cost savings
    wpp: false
