spring:
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        debug: false

wutsi:
  client-id: marketplace-manager
  application:
    email:
      welcome:
        debug: false
  platform:
    messaging:
      sms:
        type: aws
        aws:
          region: us-east-1
      push:
        type: firebase
        firebase:
          credentials: ${FIREBASE_CREDENTIALS}
      url-shortener:
        type: bitly
        bitly:
          access-token: ${BITLY_ACCESS_TOKEN}
      whatsapp:
        type: cloud
        cloud:
          access-token: ${WHATSAPP_ACCESS_TOKEN}
          phone-id: ${WHATSAPP_PHONE_ID}
    security:
      type: jwt
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}

