wutsi:
    client-id: tracking-manager
    application:
        jobs:
            compute-daily-views-kpi:
                enabled: false
    platform:
        cache:
            type: local
              #redis:
              #host: ${AMAZON_REDIS_HOST}
            #port: ${AMAZON_REDIS_PORT}
        #cache:
        #type: memcached
        #memcached:
        #aws-elastic-cache: true
        #servers: ${AMAZON_MEMCACHED_SERVERS}
        ##username: ${MEMCACHIER_USERNAME}
        ##password: ${MEMCACHIER_PASSWORD}
        ##servers: ${MEMCACHIER_SERVERS}
        ##aws-elastic-cache: false
        #ttl: 86400

        stream:
            type: rabbitmq
            rabbitmq:
                #url: ${CLOUDAMQP_URL}
                host: ${AMAZON_MQ_HOST}
                username: ${AMAZON_MQ_USERNAME}
                password: ${AMAZON_MQ_PASSWORD}
                ssl: true
                port: 5671
                dlq:
                    replay-cron: 0 */2 * * * *  # Process DLQ every 2 mins

        storage:
            type: aws
            aws:
                bucket: prod-wutsi-data
logging:
    level:
        com.wutsi.tracking.manager: INFO
