wutsi:
    client-id: tracking-manager
    application:
        jobs:
            compute-daily-views-kpi:
                enabled: false
    platform:
        cache:
            type: memcached
            memcached:
                username: ${MEMCACHIER_USERNAME}
                password: ${MEMCACHIER_PASSWORD}
                servers: ${MEMCACHIER_SERVERS}
                aws-elastic-cache: false
                ttl: 86400

        stream:
            type: rabbitmq
            rabbitmq:
                url: ${CLOUDAMQP_URL}
                dlq:
                    replay-cron: 0 */2 * * * *  # Process DLQ every 2 mins

        storage:
            type: aws
            aws:
                bucket: prod-wutsi-data
logging:
    level:
        com.wutsi.tracking.manager: INFO
