spring:

wutsi:
  client-id: tracking-manager
  application:
    jobs:
      compute-daily-views-kpi:
        enabled: false
  platform:
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
    storage:
      type: aws
      aws:
        bucket: prod-wutsi-data

logging:
  level:
    com.wutsi.tracking.manager: INFO
