spring:

wutsi:
    client-id: tracking-manager
    platform:
        cache:
            type: memcached
            memcached:
                username: ${MEMCACHIER_USERNAME}
                password: ${MEMCACHIER_PASSWORD}
                servers: ${MEMCACHIER_SERVERS}
                ttl: 86400
        stream:
            type: rabbitmq
            rabbitmq:
                host: ${CLOUDAMQP_HOST}
                username: ${CLOUDAMQP_USERNAME}
                password: ${CLOUDAMQP_PASSWORD}
                ssl: true
                port: 5671
        storage:
            type: aws
            aws:
                bucket: int-wutsi-data
