spring:

wutsi:
    client-id: tracking-manager

    platform:
        cache:
            type: memcached
            memcached:
                ttl: 86400
                aws-elastic-cache: false
                username: ${MEMCACHIER_USERNAME}
                password: ${MEMCACHIER_PASSWORD}
                servers: ${MEMCACHIER_SERVERS}

        stream:
            type: rabbitmq
            rabbitmq:
                url: ${CLOUDAMQP_URL}

        storage:
            type: aws
            aws:
                bucket: int-wutsi-data
