spring:

wutsi:
    client-id: tracking-manager
    platform:
        #cache:
        #type: memcached
        #memcached:
        #ttl: 86400
        #servers: ${AMAZON_MEMCACHED_SERVERS}
        ##username: ${MEMCACHIER_USERNAME}
        ##password: ${MEMCACHIER_PASSWORD}
        ##servers: ${MEMCACHIER_SERVERS}
        stream:
            type: rabbitmq
            rabbitmq:
                #url: ${CLOUDAMQP_URL}
                host: ${AMAZON_MQ_HOST}
                username: ${AMAZON_MQ_USERNAME}
                password: ${AMAZON_MQ_PASSWORD}
                ssl: true
                port: 5671
        storage:
            type: aws
            aws:
                bucket: int-wutsi-data
