server:
    port: 8082
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain
        min-response-size: 512

management:
    endpoint:
        health:
            show-details: always
        info:
            git:
                mode: full
    endpoints:
        web:
            exposure:
                include: "beans,flyway,health,info,scheduledtasks"

spring:
    main:
        lazy-initialization: false
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
            - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

    jackson:
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: false
            ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
        mapper:
            ACCEPT_CASE_INSENSITIVE_ENUMS: true
            ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
        default-property-inclusion: non_null

wutsi:
    client-id: tracking-manager
    application:
        name: tracking-manager
        backend:
            connection-timeout: 15000
            read-timeout: 15000
            ip-api:
                endpoint: http://ip-api.com/json
                enabled: true
        jobs:
            persister:
                cron: "0 0 * * * *" # every hour
            compute-kpi:
                cron: "0 0 */2 * * *" # every 2 hours
    platform:
        security:
            type: none
        cache:
            name: ${wutsi.application.name}
            #type: local
            type: redis
            redis:
                host: 127.0.0.1
                port: 6379

        storage:
            type: local
            local:
                directory: "${user.home}/wutsi/storage"
        stream:
            name: ${wutsi.application.name}
            type: local
            subscriptions:
                - wutsi-blog-web
        tracing:
            client-id: ${wutsi.application.name}
            device-id-provider:
                type: header

logging:
    level:
        root: INFO
        com.wutsi.tracking.manager: DEBUG
    pattern:
        console: "%d type=%level logger=%class{20} thread=%thread %m%n"
        file: "%d type=%level logger=%class{20} thread=%thread %m%n"


