spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}

wutsi:
  client-id: security-manager
  application:
    otp:
      test-addresses:
        - "+237670000001"   # MTN Demo Account: Andre Ngannou
        - "+237670000002"   # MTN Test Account #2
        - "+237670000010"   # MTN Demo Account: Nadege Simo
        - "+237670000011"   # MTN Demo Account: Joseph Nang
        - "+237670000012"   # MTN Test Account #5 (Nadine)
        - "+237690000001"   # OM  Demo Account: Maison H (business account)
        - "+237690000002"   # MTN Demo Account: Simone Atangana
        - "+237690000010"   # OM Test Account #3 (Nadine)
        - "+237690000011"   # OM Test Account #4 (Nadine)
        - "+237696074190"   # Equipe de QA de Francine
        - "+237693842356"
        - "+237690904938"
        - "+237656725264"   # Nadine
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
    messaging:
      sms:
        type: aws
        aws:
          region: us-east-1
      push:
        type: firebase
        firebase:
          credentials: ${FIREBASE_CREDENTIALS}
      url-shortener:
        type: bitly
        bitly:
          access-token: ${BITLY_ACCESS_TOKEN}
      whatsapp:
        type: cloud
        cloud:
          access-token: ${WHATSAPP_ACCESS_TOKEN}
          phone-id: ${WHATSAPP_PHONE_ID}
    security:
      token-blacklist:
        type: redis
        redis:
          url: ${REDISCLOUD_URL}
