name: workflow-engine-master

on:
  push:
    branches:
      - master
    paths:
      - 'engine/workflow-engine/**'
      - '.github/workflows/engine-workflow-engine-master.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mvn -s settings.xml --non-recursive install
          cd engine/workflow-engine
          git config user.eworkflow "actions@github.com"
          git config user.name "GitHub Actions"
          git pull
          mvn -q -B release:prepare release:perform
