name: wutsi-platform-core-master

on:
  push:
    branches:
      - master
    paths:
      - 'libs/wutsi-platform-core/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mvn -s settings.xml --non-recursive install
          cd libs/wutsi-platform-core
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git pull
          mvn -X -B release:prepare release:perform
