name: wutsi-editorjs-master

on:
    push:
        branches:
            - master
        paths:
            - 'libs/wutsi-editorjs/**'

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: JDK
                uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: 17
            -   name: Set up Maven
                uses: stCarolas/setup-maven@v4.5
                with:
                    maven-version: 3.8.2
            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                run: |
                    cd libs/wutsi-editorjs
                    git config user.email "actions@github.com"
                    git config user.name "GitHub Actions"
                    git pull
                    mvn -q -X -B release:prepare release:perform
