name: tracking-manager-sdk-kotlin-pr

on:
    pull_request:
        paths:
            - 'sdk/tracking-manager-sdk-kotlin/**'
            - '.github/workflows/sdk-tracking-manager-pull_request.yml'

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: JDK
                uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: 17
            -   name: Set up Maven
                uses: stCarolas/setup-maven@v4.5
                with:
                    maven-version: 3.8.2
            -   name: Build
                env:
                    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                run: |
                    mvn -s settings.xml --non-recursive install
                    cd sdk/tracking-manager-sdk-kotlin
                    mvn -s ../../settings.xml install
